# Generated by Django 5.0.2 on 2024-12-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='unlocked', max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rack_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackproject.rack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackproject.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='rackproject.user')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField()),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackproject.rack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rackproject.user')),
            ],
        ),
    ]
