# Generated by Django 5.0.2 on 2024-12-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rackproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='rack_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='history',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
